name: action_build_repo

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  call_workflow:
    runs-on: ubuntu-latest
    
    steps:

    - name: "Call Openwrt Build Workflow"
      uses: "Bahamut-LZX/AutoBuild-Actions/.github/workflows/AutoBuild-x86_64.yml@master"    
